Repository tsirysndr/repl, pull requests merged in 2023-10, with the labels that each got.

#3 docker: add docker compose command
  docker.ts
  main.ts
Labels: enhancement, hacktoberfest-accepted

#10 github cli plugin issue #5
  githubCLI.ts
  main.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 added git plugin
  git.ts
  main.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#14 Project structure cleaned
  main.ts
  plugins/docker.ts
  plugins/git.ts
  plugins/github-cli.ts
  src/helpers.ts
  src/plugin.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#15 chore: import all external dependencies from `deps.ts`
  deps.ts
  main.ts
Labels: enhancement

#18 Terraform plugin added
  main.ts
  plugins/terraform.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#23 feature: add brew plugin
  main.ts
  plugins/brew.ts
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#24 Issue-19: Add Bun Plugin
  main.ts
  plugins/bun.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#25 feat: add plugin for `pkgx`
  README.md
  main.ts
  plugins/pkgx.ts
Labels: enhancement, hacktoberfest

#28 feat: add plugin for `pulumi`
  README.md
  main.ts
  plugins/pulumi.ts
Labels: enhancement, hacktoberfest

#34 feat: add plugin for `tilt`
  README.md
  main.ts
  plugins/tilt.ts
Labels: enhancement, hacktoberfest

#35 feat: add plugin for `spin`
  README.md
  main.ts
  plugins/spin.ts
Labels: enhancement, hacktoberfest

#36 feat: improve autocomplete suggestions
  main.ts
Labels: enhancement

#37 feat: add plugin for `wasmer`
  README.md
  main.ts
  plugins/wasmer.ts
Labels: enhancement, hacktoberfest

#38 feat: add plugin for `dagger`
  README.md
  main.ts
  plugins/dagger.ts
Labels: enhancement, hacktoberfest

#39 feat: add plugin for `helm`
  README.md
  main.ts
  plugins/bun.ts
  plugins/dagger.ts
  plugins/docker.ts
  plugins/git.ts
  plugins/github-cli.ts
  plugins/helm.ts
  plugins/pulumi.ts
  plugins/spin.ts
  plugins/tilt.ts
  plugins/wasmer.ts
Labels: enhancement, hacktoberfest

#40 feat: add plugin for `devbox`
  README.md
  main.ts
  plugins/devbox.ts
Labels: enhancement, hacktoberfest

#41 feature: add kubectl plugin
  README.md
  main.ts
  plugins/kubectl.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#43 feat:added deno commands
  main.ts
  plugins/deno.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 feat: add plugin for `bazel`
  README.md
  main.ts
  plugins/bazel.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#48 feat: automatically install plugin if not already installed
  main.ts
  plugins/bazel.ts
  plugins/brew.ts
  plugins/bun.ts
  plugins/dagger.ts
  plugins/deno.ts
  plugins/devbox.ts
  plugins/docker.ts
  plugins/git.ts
  plugins/github-cli.ts
  plugins/helm.ts
  plugins/kubectl.ts
  plugins/pkgx.ts
  plugins/pulumi.ts
  plugins/spin.ts
  plugins/terraform.ts
  plugins/tilt.ts
  plugins/wasmer.ts
  src/plugin.ts
Labels: enhancement, hacktoberfest

#49 feat: automatically install `wasmer` plugin if not already installed
  plugins/wasmer.ts
Labels: enhancement, hacktoberfest

#50 feat: automatically install `spin` if not already installed
  plugins/spin.ts
Labels: enhancement, hacktoberfest

#51 feature: add asdf plugin
  README.md
  main.ts
  plugins/asdf.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#53 fix(asdf): split `asdf` install command into multiple commands
  plugins/asdf.ts
Labels: bug, hacktoberfest

#52 feature: Add npm plugin #21
  README.md
  main.ts
  plugins/npm.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#54 feat: add plugin for `terragrunt`
  README.md
  main.ts
  plugins/terragrunt.ts
Labels: enhancement, hacktoberfest

#57 chore: setup nix flake
  .gitignore
  deno.json
  deno.lock
  flake.lock
  flake.nix
  import_map.json
  main.ts
Labels: enhancement, hacktoberfest

#60 feature: add podman plugin
  README.md
  main.ts
  plugins/podman.ts
Labels: enhancement, hacktoberfest

#64 feat: add plugin for `nix`
  README.md
  main.ts
  plugins/nix.ts
Labels: enhancement, hacktoberfest

#65 feat: add plugin for `home-manager`
  README.md
  main.ts
  plugins/home-manager.ts
  plugins/nix.ts
Labels: enhancement, hacktoberfest

#67 feat: allow executing system commands
  main.ts
  plugins/asdf.ts
  plugins/bazel.ts
  plugins/brew.ts
  plugins/bun.ts
  plugins/dagger.ts
  plugins/deno.ts
  plugins/devbox.ts
  plugins/docker.ts
  plugins/git.ts
  plugins/github-cli.ts
  plugins/helm.ts
  plugins/home-manager.ts
  plugins/kubectl.ts
  plugins/nix.ts
  plugins/npm.ts
  plugins/podman.ts
  plugins/pulumi.ts
  plugins/spin.ts
  plugins/terraform.ts
  plugins/terragrunt.ts
  plugins/tilt.ts
  plugins/wasmer.ts
  src/helpers.ts
Labels: enhancement, hacktoberfest

#68 feat: add plugin for `flakehub`
  main.ts
  plugins/flakehub.ts
  plugins/mod.ts
Labels: enhancement, hacktoberfest

#69 feat: automatically install a command if not already installed
  src/helpers.ts
Labels: enhancement, hacktoberfest

#70 design: update color theme for banner
  repl-banner.png
Labels: documentation, enhancement

#71 fix: complete missing commands in Github CLI
  plugins/github-cli.ts
Labels: bug

#72 fix: resolve issue with the command installer
  src/helpers.ts
Labels: bug

#79 tui: add logo ASCII art
  deps.ts
  main.ts
Labels: enhancement

#80 feature: add opentofu plugin and update readme
  README.md
  plugins/mod.ts
  plugins/opentofu.ts
Labels: enhancement, hacktoberfest

#82 feat: add plugin for `fastlane`
  README.md
  plugins/fastlane.ts
  plugins/mod.ts
Labels: enhancement, hacktoberfest

#83 feat: add plugin for `gulp`
  README.md
  deps.ts
  plugins/gulp.ts
  plugins/mod.ts
Labels: enhancement, hacktoberfest

#84 feat: add plugin for `flox`
  README.md
  plugins/flox.ts
  plugins/mod.ts
Labels: enhancement, hacktoberfest

#85 feat: add plugin for `devenv`
  README.md
  plugins/devenv.ts
  plugins/mod.ts
Labels: enhancement, hacktoberfest

#86 feat: add plugin for `turbo`
  README.md
  plugins/mod.ts
  plugins/turbo.ts
Labels: enhancement, hacktoberfest

#87 feat: add plugin for `turso`
  README.md
  flake.lock
  flake.nix
  plugins/mod.ts
  plugins/turso.ts
Labels: enhancement, hacktoberfest

#88 feat: add plugin for `neon`
  README.md
  plugins/mod.ts
  plugins/neon.ts
Labels: enhancement, hacktoberfest

#89 feat: add plugin for `pscale`
  README.md
  plugins/mod.ts
  plugins/pscale.ts
Labels: enhancement, hacktoberfest

#90 feat: add plugin for `grunt`
  README.md
  plugins/grunt.ts
  plugins/mod.ts
Labels: enhancement, hacktoberfest

#92 feat: add plugin for `rtx`
  README.md
  plugins/mod.ts
  plugins/rtx.ts
Labels: enhancement, hacktoberfest

#93 feat: add plugin for `nx`
  README.md
  plugins/mod.ts
  plugins/nx.ts
Labels: enhancement, hacktoberfest

#95 fix(devbox): install nix on use devbox
  flake.nix
  main.ts
  plugins/devbox.ts
Labels: bug

#96 Add buf plugin #56
  README.md
  plugins/buf.ts
  plugins/mod.ts
Labels: enhancement, hacktoberfest

#101 feat: use `fzf` for autocompletion
  main.ts
Labels: enhancement
